version: '3.8'
services:
    react-app:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true # For hot-reload in Docker
        command: sh -c "npm install && npm run start"